sonar.projectKey=Les-Chauffagistes_ckpool-share-exporter
sonar.projectName=CKPool Share Exporter
sonar.organization=les-chauffagistes

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.cpd.exclusions=tests/**