name: CI

on:
  push:
    branches: [ "**" ]
    tags: [ "v*.*.*" ]
  pull_request:


jobs:
  test:
    uses: Les-Chauffagistes/deploy/.github/workflows/test.yml@e7eee271043b9d3c3996ca06e83c2744e972be94
    with:
      python-version: '3.13'
    secrets: inherit


  build-push:
    if: github.event_name == 'push'
    needs: test
    uses: Les-Chauffagistes/deploy/.github/workflows/build.yml@e7eee271043b9d3c3996ca06e83c2744e972be94
    with:
      service-name: ckpool-share-exporter
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      VERDACCIO_PASSWORD: ${{ secrets.VERDACCIO_PASSWORD }}
      PYPISERVER_PASSWORD: ${{ secrets.PYPISERVER_PASSWORD }}
      ORG_PAT: ${{ secrets.ORG_PAT }}